"""Updated Vote and UserVote models

Revision ID: 2fa2e0e6c1ec
Revises: 4aefd9d56ca7
Create Date: 2024-11-02 19:41:09.074090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa2e0e6c1ec'
down_revision = '4aefd9d56ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.drop_index('idx_election_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.create_index('idx_election_name', ['election_name'], unique=False)

    # ### end Alembic commands ###
